### ISSUE TITLE
Add Sneedium Browser

### ISSUE THREAD

**Issue by mymel2001-holder** [Rajaniraiyn/awesome-electron-browsers#3]
**Browser***: Sneedium
**Description**: A pro-privacy browser with built-in adblocker.
**Features**:
     - Privacy-focused URL redirecting technology.
     - Tabs
     - Ad/Tracker Blocker
     - Emoji-based UI
     - DoH

**Homepage**:  [Sneedium Landing Page](https://sneed-group.github.io/sneedium-www)
**Icon**:  [The Sneedium logo.](https://github.com/Sneed-Group/sneedium/blob/master/logo.png?raw=true)

**Additional Info**: Under a custom license that may be controversial to some. Also has "clickjacking" for the greater good (Privacy-focused URL redirecting tech) that may also be controversial, although it is for the benefit of the user and not to profit off them.

**Comment by Rajaniraiyn** [comment]
@sneedgroup-holder Thanks for the great suggestions!

It would be awesome if you could update the README with this info. A PR from you would be most welcome!

Let me know if you need any help.

**Comment by mymel2001-holder** [comment]
Created pull request. Just noticed you replied. 😅 

Anyways, closing issue now. Hope you enjoy your day. 👍
